---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels: nginx
spec:
  replicas: 3 # tells deployment to run 1 pods matching the template
  selector:
    matchlabels:
      app: nginx
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
  selector:
    app: nginx
